export const ARTICLES_RECEIVED = "ARTICLES_RECEIVED";
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const SHOW_ARTICLE_DETAILS = "SHOW_ARTICLE_DETAILS";
export const SHOW_FLASH_MESSAGE = "SHOW_FLASH_MESSAGE";
export const CLOSE_FLASH_MESSAGE = "CLOSE_FLASH_MESSAGE";
export const USER_PROFIL_RECEIVED = "USER_PROFIL_RECEIVED";
export const SEARCH_ARTICLES = "SEARCH_ARTICLES";
