export const ARTICLES_RECEIVED = "ARTICLES_RECEIVED";
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const SHOW_ARTICLE_DETAILS = "SHOW_ARTICLE_DETAILS";
